USE ROLE ACCOUNTADMIN;

-- Create warehouse, role, and database
CREATE WAREHOUSE IF NOT EXISTS INGEST1;
CREATE ROLE IF NOT EXISTS INGEST1;
GRANT USAGE ON WAREHOUSE INGEST1 TO ROLE INGEST1;
GRANT OPERATE ON WAREHOUSE INGEST1 TO ROLE INGEST1;

CREATE DATABASE IF NOT EXISTS INGEST1;
USE DATABASE INGEST1;
CREATE SCHEMA IF NOT EXISTS INGEST1;
USE SCHEMA INGEST1;

GRANT OWNERSHIP ON DATABASE INGEST1 TO ROLE INGEST1;
GRANT OWNERSHIP ON SCHEMA INGEST1.INGEST1 TO ROLE INGEST1;

-- Create user (replace YOUR_PASSWORD with a secure password)
CREATE USER INGEST1 PASSWORD='JAD_28' LOGIN_NAME='INGEST1' 
    MUST_CHANGE_PASSWORD=FALSE, DISABLED=FALSE, 
    DEFAULT_WAREHOUSE='INGEST1', DEFAULT_NAMESPACE='INGEST1.INGEST1', 
    DEFAULT_ROLE='INGEST1';

GRANT ROLE INGEST1 TO USER INGEST1;

-- Grant yourself the INGEST1 role for management
SET USERNAME=CURRENT_USER();
GRANT ROLE INGEST1 TO USER IDENTIFIER($USERNAME);
-- 5.2 Create the Table
USE ROLE INGEST1;

-- Table for car buy orders
CREATE OR REPLACE TABLE CLIENT_BUY_ORDERS (
    TXID VARCHAR(255) NOT NULL,
    RFID VARCHAR(255) NOT NULL,
    CAR_MODEL VARCHAR(255) NOT NULL,
    BRAND VARCHAR(255) NOT NULL,
    ENGINE VARCHAR(255) NOT NULL,
    HORSEPOWER NUMBER NOT NULL,
    SELL_PRICE NUMBER NOT NULL,
    PURCHASE_TIME TIMESTAMP NOT NULL,
    DAYS NUMBER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARIANT,                 
    PHONE VARCHAR(255),                  
    EMAIL VARCHAR(255),                  
    EMERGENCY_CONTACT VARIANT, 
    PRIMARY KEY (TXID)
);

CREATE OR REPLACE TABLE CAR_DETAILS (
    TXID VARCHAR(255) NOT NULL,
    CAR_MODEL VARCHAR(255) NOT NULL,
    BRAND VARCHAR(255) NOT NULL,
    ENGINE VARCHAR(255) NOT NULL,
    HORSEPOWER NUMBER NOT NULL,
    BUY_PRICE NUMBER NOT NULL,
    "TYPE" VARCHAR(255) NOT NULL,  -- ✅ quoted
    AUTONOMY NUMBER,
    CONSUMPTION NUMBER,
    RELEASE_DATE NUMBER,
    PRIMARY KEY (TXID)
);


-- Add comments for clarity
COMMENT ON TABLE CLIENT_BUY_ORDERS IS 'Customer orders for car buy inventory';
COMMENT ON COLUMN CLIENT_BUY_ORDERS.CAR_MODEL IS 'Car model';
COMMENT ON COLUMN CLIENT_BUY_ORDERS.BRAND IS 'Car brand';
COMMENT ON COLUMN CLIENT_BUY_ORDERS.ENGINE IS 'Car engine';
COMMENT ON COLUMN CLIENT_BUY_ORDERS.HORSEPOWER IS 'Car horsepower';
COMMENT ON COLUMN CLIENT_BUY_ORDERS.ADDRESS IS 'JSON: {street_address, city, state, postalcode} or NULL';
COMMENT ON COLUMN CLIENT_BUY_ORDERS.EMERGENCY_CONTACT IS 'JSON: {name, phone} or NULL';




ALTER USER INGEST1 SET RSA_PUBLIC_KEY="MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAkB9D6BqSrkdt77q64ctp
COX6uA3BfDyVRUhApaOre9kQ4xljKJ5J12DkTDGCgPQuR6jfzr0WMGJSH6l1za2z
LDg/E4a9i9ptIjxjDg+JoLOUrWmWyMubMVeFDtwemHYXVXd8BBz9XB+ed5fKrxxK
CDBIPjSwHdX71m8816cd1f0c32Q3iaHBXlLOo9HjcVQOJPIAs2epn+s7QRmj6xtV
U3r1pl3r6J/SonvGsqc5P6IcIQmVK3ZbBTWEtcUyRW7hBeJI4bkRsGG4SYm1JV1J
Fo/bvxGUhBc1kryf46+vk8Ql9v73iUFTRj9Rt4prrK+AUBA85uPup7iwW4bpshrz
NacJu7abbpunJUq2Qe1lYgNtJJIwOR5pQf6niziwz6s9Nr45Nu+LMjCVgKFiCruT
CH2+f9yKqy6wPKj2cBV7YmaN5B/zCzb4U/fyxG8S9vIKuEextQA9YSj0mu/z75sk
xLc6HMH52pt68dvkSULm78VzMSupF5Lvpj4HOHZ3OFUYsoHfQ0v3Wy/zkB1uwllB
/80Dz3w00U7mJ9gt9LciO1n936vkuo46aILzAldzqryRkDJaMg13Vac4L8ja7zgw
dvFEqOzHc91Sp+igGw5D7ppAwUQAUAz8MPGYBCPR7wWCWXZ+sPhLQBr+3mRcVmUP
Zi+qsBmtFvbibicQyqzmdW0CAwEAAQ==";



USE DATABASE INGEST1;
USE SCHEMA INGEST1.INGEST1;
-- Thing that showed me that table name didn't exist and was actually CLIENT_SUPPORT_ORDERS
SHOW TABLES LIKE 'CLIENT_SUPPORT_ORDERS_PY_COPY_INTO';





USE ROLE INGEST1;
USE DATABASE INGEST1;
USE SCHEMA INGEST1;

-- Check row count
SELECT COUNT(*) FROM CLIENT_BUY_ORDERS;

-- View sample records
SELECT * FROM CLIENT_BUY_ORDERS LIMIT 5;

-- Check data distribution by cars model    
SELECT CAR_MODEL, COUNT(*) as order_count 
FROM CLIENT_BUY_ORDERS 
GROUP BY CAR_MODEL 
ORDER BY order_count DESC;





-- Get Table data to see all the columns
DESCRIBE TABLE CLIENT_BUY_ORDERS;


-- Remove duplicates because we made some tests in the beginning and it had multiple exact rows
CREATE OR REPLACE TABLE CLIENT_BUY_ORDERS AS
SELECT DISTINCT *
FROM CLIENT_BUY_ORDERS;




