USE ACCOUNTADMIN;

-- Create warehouse, role, and database
CREATE WAREHOUSE IF NOT EXISTS INGEST1;
CREATE ROLE IF NOT EXISTS INGEST1;
GRANT USAGE ON WAREHOUSE INGEST1 TO ROLE INGEST1;
GRANT OPERATE ON WAREHOUSE INGEST1 TO ROLE INGEST1;

CREATE DATABASE IF NOT EXISTS INGEST1;
USE DATABASE INGEST1;
CREATE SCHEMA IF NOT EXISTS INGEST1;
USE SCHEMA INGEST1;

GRANT OWNERSHIP ON DATABASE INGEST1 TO ROLE INGEST1;
GRANT OWNERSHIP ON SCHEMA INGEST1.INGEST1 TO ROLE INGEST1;

-- Create user (replace YOUR_PASSWORD with a secure password)
CREATE USER INGEST1 PASSWORD='YOUR_PASSWORD' LOGIN_NAME='INGEST1' 
    MUST_CHANGE_PASSWORD=FALSE, DISABLED=FALSE, 
    DEFAULT_WAREHOUSE='INGEST1', DEFAULT_NAMESPACE='INGEST1.INGEST1', 
    DEFAULT_ROLE='INGEST1';

GRANT ROLE INGEST1 TO USER INGEST1;

-- Grant yourself the INGEST1 role for management
SET USERNAME=CURRENT_USER();
GRANT ROLE INGEST1 TO USER IDENTIFIER($USERNAME);
-- 5.2 Create the Table
USE ROLE INGEST1;

-- Table for car buy orders
CREATE OR REPLACE TABLE CLIENT_BUY_ORDERS (
    TXID VARCHAR(255) NOT NULL,
    RFID VARCHAR(255) NOT NULL,
    CAR_MODEL VARCHAR(255) NOT NULL,
    BRAND VARCHAR(255) NOT NULL,
    ENGINE VARCHAR(255) NOT NULL,
    HORSEPOWER NUMBER NOT NULL,
    PURCHASE_TIME TIMESTAMP NOT NULL,
    DAYS NUMBER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARIANT,                 
    PHONE VARCHAR(255),                  
    EMAIL VARCHAR(255),                  
    EMERGENCY_CONTACT VARIANT, 
    PRIMARY KEY (TXID)
);

-- Add comments for clarity
COMMENT ON TABLE CLIENT_BUY_ORDERS IS 'Customer orders for car buy inventory';
COMMENT ON COLUMN CLIENT_BUY_ORDERS.CAR_MODEL IS 'Car model';
COMMENT ON COLUMN CLIENT_BUY_ORDERS.BRAND IS 'Car brand';
COMMENT ON COLUMN CLIENT_BUY_ORDERS.ENGINE IS 'Car engine';
COMMENT ON COLUMN CLIENT_BUY_ORDERS.HORSEPOWER IS 'Car horsepower';
COMMENT ON COLUMN CLIENT_BUY_ORDERS.ADDRESS IS 'JSON: {street_address, city, state, postalcode} or NULL';
COMMENT ON COLUMN CLIENT_BUY_ORDERS.EMERGENCY_CONTACT IS 'JSON: {name, phone} or NULL';




ALTER USER INGEST1 SET RSA_PUBLIC_KEY="MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA7Cki41CDWdgLDi4jrHz3
bqdELWoZ0wxznTRa4t+z6wkH5AVmf2eok4KBZ2Be1ANIF9OoTcaEcnabUXF4QGq6
MAX2HZiVNhElkQQCW9ivblAMGHUw10zegMQ9wNROqblKxUZQkcmFq8t7gDpy9EUH
QEsFSy1PeUThrYEqU8U/4kGu0KciNS5Ky7ntL++nVF2vMRUTvjLAiBsrH1M52OKP
MWAs3jC+jFerY7Fq0ePLKXBiMYmUIfl0xeCN+NKb9pSm0t3Oa4q9V8zk4geCATIy
wNdLrCajAx5vzYuWXCXBf09fqh6y8AbP1awK5Nx0z22BfF3Y3x6jNJw0So3h0PBn
SZTX5xQ5mUmpA2CRj+FA7E5YitugF1oGBOlG7qo294JnESUnSAPxs6N/XFpeFEZz
UViSZ7FXPg4ta5M/GxoSlUpe+025eUZLbSyyYzbb8xy0Y85RSAPaCEVyH09FoUXi
3Bap31GxVq6O1UEXfVcLP/hn9r/VFEJYoOqa8ACLHEtEmIxDxUoImiHa5bCXGPmk
CR4JPnETCybRAK9ZHxRllVaZkM7GPvroVyDEi7fISdIDoFbBMkAsznsTJzlfyQ3p
R9OJS8BqAzBNVBzrLfpXkE8Blwttvgv0ztQgOEth49IspNMaiCZdx4Y1rPiBdOX1
TryrSjwZMaFL/2+e6h3HEfcCAwEAAQ==";


USE DATABASE INGEST1;
USE SCHEMA INGEST1.INGEST1;
-- Thing that showed me that table name didn't exist and was actually CLIENT_SUPPORT_ORDERS
SHOW TABLES LIKE 'CLIENT_SUPPORT_ORDERS_PY_COPY_INTO';





USE ROLE INGEST1;
USE DATABASE INGEST1;
USE SCHEMA INGEST1;

-- Check row count
SELECT COUNT(*) FROM CLIENT_BUY_ORDERS;

-- View sample records
SELECT * FROM CLIENT_BUY_ORDERS LIMIT 5;

-- Check data distribution by cars model    
SELECT CAR_MODEL, COUNT(*) as order_count 
FROM CLIENT_BUY_ORDERS 
GROUP BY CAR_MODEL 
ORDER BY order_count DESC;





-- Get Table data to see all the columns
DESCRIBE TABLE CLIENT_BUY_ORDERS;


-- Remove duplicates because we made some tests in the beginning and it had multiple exact rows
    CREATE OR REPLACE TABLE CLIENT_BUY_ORDERS AS
    SELECT DISTINCT *
    FROM CLIENT_BUY_ORDERS;




