USE ROLE INGEST1;
CREATE OR REPLACE TABLE CLIENT_BUY_ORDERS_PY_SNOWPIPE (
    TXID VARCHAR(255) NOT NULL,
    RFID VARCHAR(255) NOT NULL,
    CAR_MODEL VARCHAR(255) NOT NULL,
    BRAND VARCHAR(255) NOT NULL,
    ENGINE VARCHAR(255) NOT NULL,
    HORSEPOWER NUMBER NOT NULL,
    PURCHASE_TIME TIMESTAMP NOT NULL,
    DAYS NUMBER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARIANT,                 
    PHONE VARCHAR(255),                  
    EMAIL VARCHAR(255),                  
    EMERGENCY_CONTACT VARIANT, 
    PRIMARY KEY (TXID)
);

-- Create the Snowpipe to handle the ingest
CREATE OR REPLACE PIPE CLIENT_BUY_ORDERS_PIPE AS 
COPY INTO CLIENT_BUY_ORDERS_PY_SNOWPIPE
FILE_FORMAT=(TYPE='PARQUET') 
MATCH_BY_COLUMN_NAME=CASE_SENSITIVE;